<?php
/**
 * ProductResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ProductResponse"
     */
    public function testProductResponse()
    {

    }

    /**
     * Test attribute "expands"
     */
    public function testPropertyExpands()
    {

    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {

    }

    /**
     * Test attribute "product_group"
     */
    public function testPropertyProductGroup()
    {

    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {

    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {

    }

    /**
     * Test attribute "flavor"
     */
    public function testPropertyFlavor()
    {

    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {

    }

    /**
     * Test attribute "manufacturer_code"
     */
    public function testPropertyManufacturerCode()
    {

    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {

    }

    /**
     * Test attribute "ean_isbn"
     */
    public function testPropertyEanIsbn()
    {

    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {

    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {

    }

    /**
     * Test attribute "depth"
     */
    public function testPropertyDepth()
    {

    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {

    }

    /**
     * Test attribute "video"
     */
    public function testPropertyVideo()
    {

    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {

    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {

    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {

    }

}
