<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getProductBySku
     *
     * Get product by sku.
     *
     */
    public function testGetProductBySku()
    {

    }

    /**
     * Test case for getProducts
     *
     * Get list of products.
     *
     */
    public function testGetProducts()
    {

    }

    /**
     * Test case for getStatusProductBySku
     *
     * Get product status.
     *
     */
    public function testGetStatusProductBySku()
    {

    }

    /**
     * Test case for saveProduct
     *
     * Create a new product..
     *
     */
    public function testSaveProduct()
    {

    }

    /**
     * Test case for updateProduct
     *
     * Update a product..
     *
     */
    public function testUpdateProduct()
    {

    }

    /**
     * Test case for updateProductStatusBySku
     *
     * Update product status. Only sandbox.
     *
     */
    public function testUpdateProductStatusBySku()
    {

    }

}
